version: '3'
services:
  data-reports-api:
    container_name: instructor-example
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    volumes:
      - .:/workspace
    command: sleep infinity
